### PR TITLE
ultra fast triangulation

### PR DESCRIPTION
**Pull request by chenxinfeng4**
Hi, I'm a peer from neural science communitee. Thanks for your friendly package for 3D calibration. I'm also doing multiview 3D reconstruction here https://github.com/chenxinfeng4/multiview_ball_calib . We have something in common, and I got something to share. 

Here's a piece code of mine, which can speed up multiview trianglation (2D->3D) using native OpenCV API. The code will reach 20x faster (depending on the points_2d size).

### CODE REVIEW

**Comment by chenxinfeng4** [comment]
"Triangulation slower with jit decorator" in previous issue. This code, no jit at all.

**Comment by lambdaloop** [comment]
Hello @chenxinfeng4 ! Thank you for your contribution.

The triangulation you suggest has a different result from the current one. 

The new version triangulates all possible pairs and takes the median, whereas the current version triangulates all the points at once using a single SVD. I think this would result in a different result? 

We could potentially include it as an option with a switch (like fast=True) or something like that

**Comment by chenxinfeng4** [comment]
I notice that the new one has a difference with the current in triangulation result. But the difference is very slight in general cases, except when the 2D point of each view is not excat the pair -- which result in large projection error. That's a sign of sample outlier.

So, the new one has different result because it have different way to process outliers. How to assess the pression of the two methods? What's your concern?

```python
group2 = CameraGroup.load('Hand_calibration.toml')

p3d = np.array([ 152.11285309,  295.77262628, 1772.4276462 ])
p2d_exact = group2.project(p3d)
p3d_re = group2.triangulate(p2d_exact) #[ 152.11,  295.77, 1772.4 ]
p3d_fast = group2.triangulate(p2d_exact, fast=True)
assert np.allclose(p3d_fast, p3d_re) #==p3d

p2d_outlier = p2d_exact.copy()
p2d_outlier[0] += [10, 20] #pixel offset error
p3d_fast_outlier = group2.triangulate(p2d_outlier, fast=True)
p3d_outlier = group2.triangulate(p2d_outlier)
print(p3d_outlier, p3d_fast_outlier)
assert np.allclose(p3d_outlier, p3d_fast_outlier) # WILL BE FAIL

p2d_fast_outlier_proj = group2.project(p3d_fast_outlier)
p2d_outlier_proj = group2.project(p3d_outlier)
```

Compare the difference
```
>>p2d_outlier
array([[[389.59998058, 380.95252764]],   # (+10,+20) offset outlier
       [[312.17573999, 263.79173743]],
       [[275.15611537, 213.05947493]]])

>> p2d_fast_outlier_proj
array([[384.59449266, 380.67604525],
       [307.36613674, 254.19866547],
       [270.15910116, 212.91869596]])

>> p2d_outlier_proj
array([[[382.71630948, 377.30947419]],
       [[309.07071715, 257.81193347]],
       [[271.79303786, 216.33255115]]])
```

**Comment by chenxinfeng4** [comment]
I've added the fast flag. It would work fine.

**Comment by lambdaloop** [comment]
Thank you for adding the flag! 

I'm sorry it's taken me a while to review this. I'll spend some time testing it next week and will merge into next version of aniposelib if it's good.

**Comment by chenxinfeng4** [comment]
How was it going?

**Comment by lambdaloop** [comment]
I realized I'm not sure I will have to test it by itself. However, since you added the fast flag and the code looks good, I'll merge it as is. 

I also came across the Argus method for triangulation recently:
https://argus.web.unc.edu/formal-methods-and-definitions/

"Argus again uses OpenCV to reconstruct 3D points after estimating the projection matrices. For n cameras, Argus reconstructs the points for n – 1 camera pairs where all pairs contain the last camera. One camera must be contained in all the pairs to keep the coordinate system consistent. Argus takes the reconstructed points from all n – 1 pairs, normalizes them by dividing by the average distance from the origin, and averages them for the final estimation of a reconstructed point." 

It sounds kinda weird, but Argus is quite popular and maybe there is some advantage to doing it this way as well. 

This pull request then paves the way for having a mode parameter in the aniposelib triangulation (and then within anipose). We could have three modes:
 - "svd" (for original triangulation)
 - "fast" (your mode for opencv with median at the end)
 - "argus" (the triangulation described above)

**Comment by lambdaloop** [comment]
Thank you @chenxinfeng4 for your contribution!!

**Pull request merged**
